name: Run Changed Python Projects

on:
  push:
    branches: [ "**" ]
    paths-ignore:
      - ".github/workflows/*.yml"
  pull_request:
    branches: [ "**" ]
    paths-ignore:
      - ".github/workflows/*.yml"

jobs:
  detect-changes:
    runs-on: ubuntu-latest
    outputs:
      projects: ${{ steps.changes.outputs.projects }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Detect changed projects
        id: changes
        run: |
          echo "Finding changed project folders..."
          git fetch --depth=2 origin ${{ github.base_ref }} || true

          if [ "${{ github.event_name }}" = "pull_request" ]; then
            CHANGED_FILES=$(git diff --name-only origin/${{ github.base_ref }})
          else
            if git rev-parse HEAD^ >/dev/null 2>&1; then
              CHANGED_FILES=$(git diff --name-only HEAD^ HEAD)
            else
              CHANGED_FILES=$(git ls-tree --name-only -r HEAD)
            fi
          fi

          echo "Changed files:"
          echo "$CHANGED_FILES"

          PROJECTS=$(echo "$CHANGED_FILES" | grep "main.py" | xargs -r -n1 dirname | sort -u)

          echo "Detected project folders:"
          echo "$PROJECTS"

          # Use EOF format to handle spaces
          echo "projects<<EOF" >> $GITHUB_OUTPUT
          echo "$PROJECTS" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

  run-python:
    needs: detect-changes
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ "3.13.5" ]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Run changed main.py files
        run: |
          for project in ${{ needs.detect-changes.outputs.projects }}; do
            echo "Running $project/main.py"
            python "$project/main.py" || exit 1
          done
